### ISSUE TITLE
This is literally Makerkit.dev

### ISSUE THREAD

**Issue by Gbuomprisco** [cameronking4/next-shadcn-stripe-multitenant-saas#3]
Hi, founder of Makerkit.dev.

You took Makerkit and open sourced it. Please take it down.

Attaching some proof: this **only one of the many files that are the same ones**. Down to the kb.

<img width="875" alt="image" src="https://github.com/user-attachments/assets/cae4cdf5-84e5-4e08-adf7-ff2a442a96f2">
<img width="715" alt="image" src="https://github.com/user-attachments/assets/4e3c9138-7c53-4853-9b55-8783cb4fee88">

**Comment by bigscotia10** [comment]
Cameron - 
Please take this down ASAP. This is an unauthorized open-sourcing of Makerkit.dev.

**Comment by jperasmus** [comment]
@cameronking4 This is not how you want to do it. Stealing someone's work is not how you make friends in this industry.

**Comment by cameronking4** [comment]
Dang! I hired help to make a clone and thank you for pointing this out. You can see from the history. He must've bought template instead of implementing from scratch. Bummer but agreed I'll take down.

**Comment by cameronking4** [comment]
You can verify I never bought template or had license. Very sorry about this.

**Comment by cameronking4** [comment]
Huge lesson learned, will do things myself going forward, again my sincere apologies.

**Comment by Gbuomprisco** [comment]
Hi @cameronking4 - I appreciate taking quick action. If you could send me who sold you this I would be grateful. Hope you get your money back.

**Comment by cameronking4** [comment]
@Gbuomprisco it's ok I don't mind on money lost here, I'm truly sorry for this, especially to you @Gbuomprisco. I had purest of intentions and very disappointed this happened. I will delete this repo entirely.
